# GitHub Actions workflow for C++ build and test

name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential make g++ cmake libgtest-dev
          sudo cmake -S /usr/src/gtest -B /usr/src/gtest/build
          sudo cmake --build /usr/src/gtest/build
          sudo cp /usr/src/gtest/build/lib/libgtest*.a /usr/lib/

      - name: Build project
        run: make

      - name: Build and run all tests (with GTest)
        run: |
          if make -q utest-ka-scheme 2>/dev/null; then
            make utest-ka-scheme;
          else
            echo "No utest-ka-scheme target in Makefile, skipping build.";
          fi
          if [ -x bin/utest-ka-scheme ]; then
            ./bin/utest-ka-scheme;
          else
            echo "No bin/utest-ka-scheme executable found.";
          fi
        shell: bash
